module.exports = {
  ACCOUNTS_LIST: 'accounts:list',
  ACCOUNTS_CREATE: 'accounts:create',
  ACCOUNTS_DELETE: 'accounts:delete',
  ACCOUNTS_SET_ACTIVE: 'accounts:setActive',
  ACCOUNTS_GET_ACTIVE: 'accounts:getActive',
  ACCOUNTS_LOGIN_MICROSOFT: 'accounts:loginMicrosoft',
  ACCOUNTS_CANCEL_MS_LOGIN: 'accounts:cancelMsLogin',

  INSTANCES_LIST: 'instances:list',
  INSTANCES_CREATE: 'instances:create',
  INSTANCES_UPDATE: 'instances:update',
  INSTANCES_DELETE: 'instances:delete',
  INSTANCES_SET_ACTIVE: 'instances:setActive',
  INSTANCES_GET_ACTIVE: 'instances:getActive',

  VERSIONS_LIST: 'versions:list',
  VERSIONS_LIST_INSTALLED: 'versions:listInstalled',
  VERSIONS_DELETE_INSTALLED: 'versions:deleteInstalled',
  VERSIONS_LIST_FABRIC_LOADERS: 'versions:listFabricLoaders',
  VERSIONS_LIST_FORGE_VERSIONS: 'versions:listForgeVersions',
  VERSIONS_INSTALL_VANILLA: 'versions:installVanilla',
  VERSIONS_INSTALL_FABRIC: 'versions:installFabric',
  VERSIONS_INSTALL_FORGE: 'versions:installForge',
  VERSIONS_INSTALL_PROGRESS: 'versions:installProgress',
  VERSIONS_INSTALL_LOG: 'versions:installLog',

  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_BROWSE_JAVA: 'settings:browseJava',
  SETTINGS_VALIDATE_JAVA: 'settings:validateJava',

  LAUNCH_START: 'launch:start',
  LAUNCH_CANCEL: 'launch:cancel',
  LAUNCH_PROGRESS: 'launch:progress',
  LAUNCH_LOG: 'launch:log',
  LAUNCH_EXIT: 'launch:exit',
  LAUNCH_ERROR: 'launch:error',
};
