module.exports = {
  ACCOUNTS_LIST: 'accounts:list',
  ACCOUNTS_DELETE: 'accounts:delete',
  ACCOUNTS_SET_ACTIVE: 'accounts:setActive',
  ACCOUNTS_GET_ACTIVE: 'accounts:getActive',
  ACCOUNTS_LOGIN_MICROSOFT: 'accounts:loginMicrosoft',
  ACCOUNTS_CANCEL_MS_LOGIN: 'accounts:cancelMsLogin',
  ACCOUNTS_REFRESH_ACTIVE_SESSION: 'accounts:refreshActiveSession',

  INSTANCES_LIST: 'instances:list',
  INSTANCES_CREATE: 'instances:create',
  INSTANCES_UPDATE: 'instances:update',
  INSTANCES_DELETE: 'instances:delete',
  INSTANCES_SET_ACTIVE: 'instances:setActive',
  INSTANCES_GET_ACTIVE: 'instances:getActive',

  VERSIONS_LIST: 'versions:list',
  VERSIONS_LIST_INSTALLED: 'versions:listInstalled',
  VERSIONS_DELETE_INSTALLED: 'versions:deleteInstalled',
  VERSIONS_LIST_FABRIC_LOADERS: 'versions:listFabricLoaders',
  VERSIONS_LIST_FORGE_VERSIONS: 'versions:listForgeVersions',
  VERSIONS_INSTALL_VANILLA: 'versions:installVanilla',
  VERSIONS_INSTALL_FABRIC: 'versions:installFabric',
  VERSIONS_INSTALL_FORGE: 'versions:installForge',
  VERSIONS_INSTALL_PROGRESS: 'versions:installProgress',
  VERSIONS_INSTALL_LOG: 'versions:installLog',

  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_BROWSE_JAVA: 'settings:browseJava',
  SETTINGS_VALIDATE_JAVA: 'settings:validateJava',

  MODS_SEARCH: 'mods:search',
  MODS_LIST_INSTALLED: 'mods:listInstalled',
  MODS_INSTALL: 'mods:install',
  MODS_REMOVE: 'mods:remove',
  MODS_SET_ENABLED: 'mods:setEnabled',
  MODS_OPEN_FOLDER: 'mods:openFolder',
  MODS_IMPORT_LOCAL: 'mods:importLocal',
  MODS_UPLOAD_LOCAL: 'mods:uploadLocal',
  MODS_AUTO_RESOLVE_VERSION: 'mods:autoResolveVersion',

  RESOURCEPACKS_SEARCH: 'resourcepacks:search',
  RESOURCEPACKS_LIST_INSTALLED: 'resourcepacks:listInstalled',
  RESOURCEPACKS_INSTALL: 'resourcepacks:install',
  RESOURCEPACKS_REMOVE: 'resourcepacks:remove',
  RESOURCEPACKS_SET_ENABLED: 'resourcepacks:setEnabled',
  RESOURCEPACKS_OPEN_FOLDER: 'resourcepacks:openFolder',

  MC_SETTINGS_GET: 'mcSettings:get',
  MC_SETTINGS_SET: 'mcSettings:set',

  LAUNCH_START: 'launch:start',
  LAUNCH_CANCEL: 'launch:cancel',
  LAUNCH_PROGRESS: 'launch:progress',
  LAUNCH_LOG: 'launch:log',
  LAUNCH_EXIT: 'launch:exit',
  LAUNCH_ERROR: 'launch:error',
  LAUNCH_CRASH: 'launch:crash',
  LAUNCH_COMPAT_WARNING: 'launch:compatWarning',
  LAUNCH_SNAPSHOT_WARNING: 'launch:snapshotWarning',
};
